### ISSUE TITLE
Bad encoding in subject and body message

### ISSUE THREAD

**Issue by TrueShutDown** [SSilence/php-imap-client#112]
I'm getting email via getMessage() function and subject and body are not poperly decoding.
 
dumped results from getMessage function:
```
 header => stdClass object {
    subject => (string) =?UTF-8?B?dGVzdDEgxIXFvMW6xIfEh8WbxbzFusSHxIU=?=
    (...)
  }
  message => stdClass object {
    plain => (string) Tutaj jest tre=C5=9B=C4=87

*tutaj wi=C4=99cej tre=C5=9Bci

Osadzony obraze:
```

The subject should contain:

`test1 ążźććśżźćą`

and body
```
Tutaj jest treść

tutaj więcej treści

Osadzony obraze
```

**Comment by xXXIMMATTHEWXXx** [comment]
Hmm. Let me investigate

**Comment by xXXIMMATTHEWXXx** [comment]
This may be due to the fact that those are special characters. We currently do not support them so let me get right on that!

**Comment by TrueShutDown** [comment]
Before update special (polish) characters worked properly.

**Comment by sergey144010** [comment]
Try to use it.
`
$subject = imap_mime_header_decode ( $obj->header->subject );
$subject = imap_mime_header_decode ( $obj->message->plain);
`
And write the result.

**Comment by sergey144010** [comment]
I need your
`
$imap->incomingMessage->message->info
`
or at least
`
$imap->incomingMessage->message->info[0]->structure->encoding
or
$imap->incomingMessage->message->info[1]->structure->encoding
`

**Comment by TrueShutDown** [comment]
imap_mime_header_decode ($obj->header->subject)

```
array(1) (
  [0] => stdClass object {
    charset => (string) UTF-8
    text => (string) test1 ążźććśżźćą
  }
)
```
imap_mime_header_decode ( $obj->message->plain)
```
array(1) (
  [0] => stdClass object {
    charset => (string) default
    text => (string) Tutaj jest tre=C5=9B=C4=87

*tutaj wi=C4=99cej tre=C5=9Bci

Osadzony obraze:

Obrazek
*

  }
)
```
$imap->incomingMessage->message->info

```
array(1) (
  [0] => stdClass object {
    structure => stdClass object {
      type => (int) 0
      encoding => (int) 1
      ifsubtype => (int) 1
      subtype => (string) PLAIN
      ifdescription => (int) 0
      ifid => (int) 0
      lines => (int) 8
      bytes => (int) 80
      ifdisposition => (int) 0
      ifdparameters => (int) 0
      ifparameters => (int) 1
      parameters => array(2) (
        [0] => stdClass object {
          attribute => (string) CHARSET
          value => (string) utf-8
        }
        [1] => stdClass object {
          attribute => (string) FORMAT
          value => (string) flowed
        }
      )
    }
    body => (string) Tutaj jest tre=C5=9B=C4=87

*tutaj wi=C4=99cej tre=C5=9Bci

Osadzony obraze:

Obrazek
*

  }
)
```

**Comment by sergey144010** [comment]
To fix the encoding problem in your message, I need your help. I need you to install this package from my repository, as follows.
`
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/sergey144010/php-imap-client",
			"packagist": false
        }
    ],
    "require": {
        "SSilence/php-imap-client": "dev-master"
    }
}
`
And showed me again
`
$imap->incomingMessage->message->info
`

**Comment by TrueShutDown** [comment]
Your repo working :) subject and body have correct encoding
```
Array
(
    [0] => stdClass Object
        (
            [structure] => stdClass Object
                (
                    [type] => 0
                    [encoding] => 1
                    [ifsubtype] => 1
                    [subtype] => PLAIN
                    [ifdescription] => 0
                    [ifid] => 0
                    [lines] => 8
                    [bytes] => 80
                    [ifdisposition] => 0
                    [ifdparameters] => 0
                    [ifparameters] => 1
                    [parameters] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [attribute] => CHARSET
                                    [value] => utf-8
                                )

                            [1] => stdClass Object
                                (
                                    [attribute] => FORMAT
                                    [value] => flowed
                                )

                        )

                )

            [body] => Tutaj jest treść

*tutaj więcej treści

Osadzony obraze:

Obrazek
*

        )

)
```

**Comment by xXXIMMATTHEWXXx** [comment]
@sergey144010. Your repos latest code is working. Please make sure your code is stable and documented and make a pull request. I will gladly merge it.

**Comment by sergey144010** [comment]
So this is a very interesting question. As you can see your mail server gives this letter and says that it is encoded with 8bit encoding. You can see it here:
```php
structure->encoding = 1
# http://php.net/manual/ru/function.imap-fetchstructure.php
```
So the body of the letter SHOULD BE decoded with the imap_8bit () method. This is logical.
That now happens in the current version in this repository.
If this is removed, then it will not be logical.
Because this is the reason for decoding or not.
It turns out that your body is encoded, and you do not need to decode it. This is not the correct logic.
And the encoding is known in advance and given by the server. What's strange.
So you need to find out why this is happening to your mail server. Which server are you using?
In the meantime, only you need to encode the body of the letter back with the function imap_qprint () and the letter will be displayed correctly.
```php
$str = "Tutaj jest tre=C5=9B=C4=87
*tutaj wi=C4=99cej tre=C5=9Bci
Osadzony obraze:
Obrazek
*
";

var_dump(imap_qprint($str));

string(78) "Tutaj jest treść
*tutaj więcej treści
Osadzony obraze:
Obrazek
*
"
```

And with subject message, everything is clear, we'll fix it soon, but for now use imap_mime_header_decode() method.

**Comment by sergey144010** [comment]
The question is whether the encoding 8bit should be decoded?

**Comment by xXXIMMATTHEWXXx** [comment]
I think **_everything_** should be decoded. Devs don't need to worry about a // hack comment that lets they know they are hacking around our library. So yes

**Comment by sergey144010** [comment]
I changed it. Pull. Check.

**Comment by xXXIMMATTHEWXXx** [comment]
Merged. Please check your code with out latest updates

**Comment by xXXIMMATTHEWXXx** [comment]
@TrueShutDown is this issue fixed?

**Comment by xXXIMMATTHEWXXx** [comment]
We assume this issue has been fixed @TrueShutDown. We have merged pull request that we believe fix this issue!

**Comment by sloothword** [comment]
Not usre if this is related, but I tried with the latest update (eaf55dbb0772d5a209b62e2da875ae17c6fcbf47) and still get subjects like
> =?UTF-8?Q?Spanisch_Pr=c3=bcfung?=

instead of
> Spanisch Prüfung

**Comment by sergey144010** [comment]
You did ``composer update``?

**Comment by sloothword** [comment]
Yep. Did it again (no change):

>  Updating ssilence/php-imap-client dev-master (eaf55db => 0fbccd3)
    Checking out 0fbccd3fe6d5fc1965102eb7f6fd96679f7c1de6

**Comment by sloothword** [comment]
ok i started debugging it:

```
IncomingMessage.php
private function init()
    {
        $structure = $this->imapFetchstructure();
        $this->structure = $structure;
        if(isset($structure->parts)){
            $countSection = count($structure->parts);
            $this->countAttachment = $countSection-1;
        };
        $this->getCountSection();
        $this->getAttachment();
        $this->getBody();
        // HERE, HEADER IS EMPTY
        $this->decode();
        // HERE, HEADER IS STILL EMPTY
        $header = $this->imapFetchOverview();
        $this->header = $header[0];
        // NOW, HEADER IS SET, BUT NOT DECODED
        $this->header->details = $this->imapHeaderInfo();
    }
```

If i move `$this->decode();` to the end of the function it works.

**Comment by sergey144010** [comment]
I understand, now we'll fix it.

**Comment by sergey144010** [comment]
Please do `composer update` . Try it. And if everything is okay, we cover the topic.

**Comment by xXXIMMATTHEWXXx** [comment]
@TrueShutDown ping
