### ISSUE TITLE
Embedded images not showing up

### ISSUE THREAD

**Issue by SonnyLCD** [SSilence/php-imap-client#57]
Hi

Thanks for your great work on this library. The last update fixed a lot and added some really nice features.

One thing that I had to fix, at least to get working with my mail server, was a mixup between `$uid` and `$msg_no`:

```
public function getMessage($id, $withbody = true, $embed_images = false)
{
	// CONVERT $uid TO $msg_number
    	$msg_number = imap_msgno($this->imap,$id);
	return $this->formatMessage($msg_number, $withbody, $embed_images);
}
```
The PHP imap library seems to be is a bit of a mess, some functions expect $uid and others $msg_number. So for future releases it might be a good idea to distinguish between $uid and $msg_number, instead of just $id for both ?

Download links for attachments works great now.
Both for inline attachments (Mac Mail) and for regular attachments.

But, one thing that stopped working and I haven't been able to fix it yet, is that images embedded in the email does not render. The `$mail['body_embed']` does not substitute the reference with the base64 encoded string. The HTML returned for the image looks like this:

`<img src="cid:ii_158df264e4927608" alt="Inline image 1" width="40" height="40">`
(Just shows a broken image)

And when sent from Mac Mail as inline attachment it looks like this:

`<img name="test.gif" apple-inline="yes" id="14107C9B-A1FC-45E0-8F1F-D15CF2710C8E" height="40" width="40" apple-width="yes" apple-height="yes" src="cid:6B72E216-6751-4981-A1C7-3EBA0EC741E7@homerouter.cpe" class="">`

But as mentioned, the download links works, so the script do find the attachments.

Before the last update I had embedded images working from non-Mac Mail...

Thanks for developing a very nice imap client!

**Comment by natanfelles** [comment]
I think that we have to change the way we get individual emails and instead of picking up the `id` (that can be changed if changes are made in the email box, move, delete, etc) and we should use the unique identifier `uid` .

But this will also change the way that users of this library use their methods. I think it is necessary to create a new version or make it very explicit.

**Comment by SonnyLCD** [comment]
exactly, there are functions to switch between the 2, so is pretty simple:

From UID to message number:

`$msg_number = imap_msgno($this->imap,$uid);`

and from message number to UID:

`$uid = imap_uid($this->imap,$msg_number);`

**Comment by xXXIMMATTHEWXXx** [comment]
I like this!

**Comment by xXXIMMATTHEWXXx** [comment]
This was fixed with #58. If it was not, please comment back

**Comment by SonnyLCD** [comment]
Thanks xXXIMMATTHEWXXx

I will check with latest and get back if problem persists...

**Comment by SonnyLCD** [comment]
Hi!

I have tested, and is same with the latest version. I am developing an application where I register this Imap class as a service in a Phalcon PHP based application. We are using a Postfix mail server.

Images doesn't show up, only broken image. As example the source for the image file says:

`<img apple-inline="yes" id="95D04268-097B-47AD-A1E1-A32589291545" height="40" width="40" apple-width="yes" apple-height="yes" src="cid:586581FE-7D92-4E43-9C2B-4B6DBB7FD95D@homerouter.cpe" class="">`

Depending from where mail is sent, which Internet provider, there will be something appended to the CID, like above from one location is: 

`src="cid:586581FE-7D92-4E43-9C2B-4B6DBB7FD95D@homerouter.cpe"`

but when mail is sent from a Telefonica internet connection in Spain I got: 

`src="cid:DCFDDECD-8019-4FB3-91AD-92F36E3B6816@telefonica.net"`

Have you seen this before ? maybe it is the Postfix server that appends this @nnn rubbish ?

One should cut from the @ and what is after that, with regex or something ?

**Comment by xXXIMMATTHEWXXx** [comment]
It will be looked into

**Comment by SonnyLCD** [comment]
Just an update. This library works great, I only have one issue left, which is images in messages.

Latest version seems to have changed a bit, now the image reference looks nicer, tried sending from both Gmail and Apple Mail. 

Apple Mail sends images inline and there in no trace of the images in the emails, but they show up as attachments and can be downloaded without problems. 

Gmail adds images, but the html that the library returns looks like below, which ofcourse does not render the image:

`<img src="cid:ii_159b3053ec1b2508" alt="Inline image 1" width="67" height="67">`

Maybe this could point to a solution ?

Does anyone have it working and showing images correctly ?

**Comment by SonnyLCD** [comment]
I have been running through the script to find where things goes wrong.

And what I found is that the function:

`formatMessage()`

Returns this below (some html in message removed to simplify), where the icon.png file should show up embedded in email and not just as an attachment:

```
Array
(
    [to] => Array
        (
            [0] => someone else <someoneelse@domain.com>
        )

    [from] => someone <someone@gmail.com>
    [date] => Wed, 18 Jan 2017 20:20:02 +0100
    [udate] => 1484767205
    [subject] => Gmail example. Embed + Attachment
    [priority] => 3
    [uid] => 48
    [id] => 48
    [flagged] => 
    [unread] => 1
    [answered] => 
    [deleted] => 
    [size] => 19974
    [body] => Hello<br><img src="cid:ii_159b3053ec1b2508" alt="Inline image 1" width="67" height="67"><br>world...

    [html] => 1
    [attachments] => Array
        (
            [0] => Array
                (
                    [name] => icon.png
                    [size] => 7352
                    [disposition] => inline
                    [reference] => <ii_159b3053ec1b2508>
                )
            [1] => Array
                (
                    [name] => test.xls
                    [size] => 8406
                    [disposition] => attachment
                    [reference] => 
                )
        )
)
```

So we have the correct reference, plus we have the image file as an attachment, -so far so good.

But seems that substituting the reference with the base64 encoded image string does not work ?

**Comment by GIAPB** [comment]
Hello im a bot that works for @xXXIMMATTHEWXXx :). It does seem we are close. I will continue to look into this

**Comment by SonnyLCD** [comment]
seems fixed in latest release, so will close this...

**Comment by xXXIMMATTHEWXXx** [comment]
Thanks!
